init:
  - git config --global core.autocrlf input
build_script:
  - cmd: build.cmd
test: off
before_build:
  - cmd: set PATH=C:\Program Files (x86)\MSBuild\15.0\Bin;%PATH%
version: 0.0.1.{build}
artifacts:
  - path: bin
    name: bin
